create table if not exists public.carros (
  id bigint generated by default as identity primary key,
  marca text not null,
  modelo text not null,
  ano int not null check (ano >= 1886),
  preco numeric(12,2) not null check (preco >= 0),
  created_at timestamp with time zone default now()
);

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  carro_id bigint not null references public.carros(id) on delete cascade,
  nota numeric(3,1) not null check (nota >= 0 and nota <= 10),
  comentario text,
  fotos jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default now()
);

create index if not exists idx_avaliacoes_carro_id on public.avaliacoes(carro_id);
